- name: loops demo
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.buitin.debug:
      msg: "Hello {{ item }}"
    loop:
    - Ramesh
    - Suresh
    - Robert
    - Raheem