- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variables
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to uppercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }} "

  - name: convert to lowercase
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }} "

  - name: get the unique values
    vars:
      numbers: [1,2,3,45,3,2,9,0]
    ansible.builtin.debug:
      msg: " {{ numbers | unique }} "

  - name: get the min and max
    vars:
      numbers: [1,2,3,45,3,2,9,0]
    ansible.builtin.debug:
      msg: "min: {{ numbers | min }}, max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course:
        name: "devops with aws"
        duration: 120
        trainer: "sai"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"