- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0cdb6ea5293f1a031 #we will get this from aws server networking and subnet id
    sg_id: "sg-001c2affbe1e077cf" #get this from aws server security Security groups 
    ami_id: "ami-09c813fb71547fc4f" #get this from aws server details ami id
    instances: 
    - mysql
    - backend
    - frontend
    zone: dawsconnect.org
  tasks:
  - name: Install boto3 and botocore #to install below 2 dependencies as ansible is developed on top of python and if ansible wants to connect to aws using sdk we need boto3 and botocore to be installed in python and also 3.9 is the version of ansible this version may change to get the versions we need to use ansible --version 
    ansible.builtin.pip3.9:
    name:
    - boto3
    - botocore
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances #we get entire output as we need this output to create r53 records and private ip also we will get fro here

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  #private ip r53
  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.dawsconnect.org 1st item is for loop 2nd item is key for mysql value 
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}" #item is for loop
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: create r53 public records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #dawsconnect.org
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}" #item is for loop
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: ec2_instances.results.item == "frontend"